### ISSUE TITLE
Remove date needed by for Pittsburg

### ISSUE THREAD

**Issue by AngelaLuo49021** [Covaid-co/covaid-web#27]
From Pittsburg: 
- "Remove the "needed by" drop down menu in the request form. The "needed by" menu has posed some challenges for us with capacity. We'd like to get rid of it, and..."
^ Could probably remove this for covaid in general since I dont think we follow it. Replace by date submitted on the org portal. 
- "Add a message about response timeline. In place of the "needed by" drop down menu, we'd like to add a note: "Thanks for submitting a request to Pgh Mutual Aid. We're getting a lot of requests right now, so it may take us up to a week to reach back out to you. If you need support more immediately, check out https://www.pittsburghmutualaid.com/resources for other local resources that may be able to connect sooner. Take good care."
Thank you so much for all that you do! (edited) "
^ for all other orgs, either leave it blank or just rework the above message to be more generic

**Comment by shresta4** [comment]
- [ ] Translate to spanish 
- [ ] Add msg at the end of the request form 
- [ ] Convert needed by to created by
